In [1]:
from __future__ import absolute_import, division, print_function

import numpy as np
import tensorflow as tf
import tensorflow.contrib.eager as tfe

# Set Eager API
print("Setting Eager mode...")
tfe.enable_eager_execution()

Setting Eager mode...


In [93]:
# Define constant tensors
print("Define constant tensors")
a = tf.constant(2)
b = tf.constant(3)
print("a = %i" % a)
print("b = %i" % b)
print("a's type: ", type(a))
print("b's type: ", type(b))

Define constant tensors
a = 2
b = 3
a's type:  <class 'EagerTensor'>
b's type:  <class 'EagerTensor'>


In [107]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")
c = a + b
d = a * b
print("a + b = %i" % c)
print("a * b = %i" % d)
print("c's type: ", type(c))
print("d's type: ", type(d))

Running operations, without tf.Session
a + b = 5
a * b = 6
c's type:  <class 'EagerTensor'>
d's type:  <class 'EagerTensor'>


In [255]:
# Full compatibility with Numpy
print("Mixing operations with Tensors and Numpy Arrays")

# Define constant tensors
a = tf.constant([[2., 1.],
                 [1., 0.]], dtype=tf.float32)
b = np.array([[3., 0.],
              [5., 1.]], dtype=np.float32)
print("Tensor:\na =\n%s" % a)
print("NumpyArray:\nb =\n%s" % b)
print("a's type: ", type(a))
print("b's type: ", type(b), b.dtype)

a = tf.constant([[2., 1.],
                 [1., 0.]])
b = np.array([[3., 0.],
              [5., 1.]])
print("Tensor:\na =\n%s" % a)
print("NumpyArray:\nb =\n%s" % b)
print("a's type: ", type(a))
print("b's type: ", type(b), b.dtype)

Mixing operations with Tensors and Numpy Arrays
Tensor:
a =
tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
b =
[[3. 0.]
 [5. 1.]]
a's type:  <class 'EagerTensor'>
b's type:  <class 'numpy.ndarray'> float32
Tensor:
a =
tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
b =
[[3. 0.]
 [5. 1.]]
a's type:  <class 'EagerTensor'>
b's type:  <class 'numpy.ndarray'> float64


In [258]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")
c = a + b
d = tf.matmul(b, a)
print("a + b =\n%s" % c)
print("a * b =\n%s" % d)
print("c's type: ", type(c))
print("d's type: ", type(d))

Running operations, without tf.Session


InvalidArgumentError: cannot compute MatMul as input #1 was expected to be a double tensor but is a float tensor [Op:MatMul] name: MatMul/

In [236]:
print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])
        print(type(a[i][j]))

Iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
<class 'EagerTensor'>
tf.Tensor(1.0, shape=(), dtype=float32)
<class 'EagerTensor'>
tf.Tensor(1.0, shape=(), dtype=float32)
<class 'EagerTensor'>
tf.Tensor(0.0, shape=(), dtype=float32)
<class 'EagerTensor'>
